name: Build and save my Docker image to a regitry

on:
  push:
    branches:
      - main  # Déclenchement lorsque le code est poussé sur main
    paths:
      - 'todo-app/src/backend/**'  # Se déclenche uniquement si des fichiers dans 'src/backend' sont modifiés

env:
  REG_NAME: "exo.container-registry.com" # Nom du registre sans "azurecr.io"
  IMAGE_NAME: "todo-app" # Nom de votre image dans acr

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest #créer une petite vm ubuntu 

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3 # copie tout le code comme un git clone sur la vm et elle va executer les steps.

      - name: connection à la repository
        run: |
          docker login -u quentin.badoud@edufr.ch -p ${{ secrets.DOCKER_PASSWORD }} $REG_NAME

      - name: build docker image
        run: |
          cd ./todo-app/src/backend
          docker build -t ${{ env.REG_NAME }}/c213-emf/${{ env.IMAGE_NAME }} .

      - name: tag docker image
        run: |
          docker tag ${{ env.REG_NAME }}/c213-emf/${{ env.IMAGE_NAME }} ${{ env.REG_NAME }}/c213-emf/${{ env.IMAGE_NAME }}:CRJ

      - name: push sur la registry
        run: |
          docker push ${{ env.REG_NAME }}/c213-emf/${{ env.IMAGE_NAME }}:CRJ