# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - 210-web-app-crausaz-jules

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://acr300621210.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_9e3a5d149c1d4df48861b21ead37f71d }}
        password: ${{ secrets.AzureAppService_ContainerPassword_eeaf8a3d66864b8a8f4d65f53fe4ebc1 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: acr300621210.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_9e3a5d149c1d4df48861b21ead37f71d }}/todo-app:${{ github.sha }}
        file: ../todo-app/src/backend/Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: '210-web-app-crausaz-jules'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_f0f732e43af94affa57a94c2025632fc }}
        images: 'acr300621210.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_9e3a5d149c1d4df48861b21ead37f71d }}/todo-app:${{ github.sha }}'